### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by taki0112** [AlexiaJM/RelativisticGAN#1]
Hi
Very nice work. Thanks for sharing ! 

I have some questions 
1. when make the `256x256` images, you used `PACGAN2` ! In your paper, you concat `x1` & `x2`
`x1` and `x2` are same images ? or different image ?

2. In RelativisticGAN, doesn't see `mode collapse` ? 

3. What is the performance of `RLSGAN`? I only see the RaLSGAN in your paper.

4. Is `batch_size` not important  for RelativisticGAN ? 

Thank you

**Comment by AlexiaJM** [comment]
1. Different images concatenated in the color channels. So the two images 3x256x256 now become 6x256x256. So you have to sample 2*batch_size images.
2. There is some with 256x256 but not too much, FID would be high if there was a lot of mode collapse. See for yourself: https://imgur.com/a/pKI3PYa
3. I did not try but it would be worth investigating. I only have a Geforce 1060 so I have to prioritize.
4. I only used 32, but I assume not. For SGAN though larger batch size is a problem, it might worth comparing.

**Comment by taki0112** [comment]
Thank you
