### ISSUE TITLE
if  dont't resample the data again, what will happen

### ISSUE THREAD

**Issue by 2018hello** [AlexiaJM/RelativisticGAN#18]
hi
I see in Relativistic average Standard GAN code. 
It said "You may want to resample again from real and fake data"
And so,if I  dont't resample the data again, what will happen?

**Comment by AlexiaJM** [comment]
Nothing, it's just add some stochasticity/randomness. It doesn't change results much, so it might just be personal preferences.

You train D using real sample A and and fake sample B. 
You train G using real sample A and and fake sample B. 
vs
You train D using real sample A and and fake sample B. 
You train G using real sample C and and fake sample D.
