### ISSUE TITLE
 sigmoid activation in last layer of the generator?

### ISSUE THREAD

**Issue by ahmed-fau** [AlexiaJM/RelativisticGAN#19]
Hi,

Thanks for this interesting work .. just one question regarding the following comments of the code snippet you have provided in the readme page:

> No sigmoid activation in last layer of **generator** because BCEWithLogitsLoss() already adds it

> No activation in **generator**

Is this true? or you mean the discriminator is what should include/exclude sigmoid activation?

Thanks

**Comment by AlexiaJM** [comment]
You are right, it's the discriminator, not the generator. Fixed it.
