### ISSUE TITLE
something wrong in SGAN

### ISSUE THREAD

**Issue by JinKe-11** [AlexiaJM/RelativisticGAN#23]
Everything seems great in RSGAN and RaSGAN, but when I test  SGAN in CAT 64x64, it can not generator anything with lr=0.0002. Shall I change it ?

**Comment by JinKe-11** [comment]
I find in [https://ajolicoeur.wordpress.com/cats/](url) that the lrD=.00005 and lrG=.0002, but in the paper that the SGAN lr=.0002 without any changing, which one should I apply. Shall I replace criterion in SGAN loss with BCE_stable ?

**Comment by AlexiaJM** [comment]
Try BCE_stable, this should make it much more stable. See new code version which uses BCE_stable: https://github.com/AlexiaJM/relativistic-f-divergences/blob/master/GAN.py.

**Comment by JinKe-11** [comment]
Thank you for your reply, I will try it
