### ISSUE TITLE
Gradient argument in the paper

### ISSUE THREAD

**Issue by AceChuse** [AlexiaJM/RelativisticGAN#4]
I read your paper. It's really a good job. But the thing which I don't understand is the gradient of generator. Why is there $C(G(z))$ in the function. And I don't find the form of $J_{\theta}G(z)$ in the paper. Is that the derivative of $G(z)$ to $\theta$ ? 
If you can help me, I will be very grateful.

**Comment by AlexiaJM** [comment]
Yes. See appendix, it's the chain rule, gradient_theta of C(G(z)) is C(G(z)) * grad_x C(G(z)) * J_theta G(z). J_theta is the Jacobian matrix. When you take the gradient of D, D is a scalar, so the derivate over all x, is a vector. But here G outputs many values (3x32x32 for 32x32 images), so you need to take the derivative of all 3x32x32 putouts for all theta. So you can't just take the vector, you need the Jacobian. That's all it is. Look up https://en.wikipedia.org/wiki/Non-linear_least_squares, it talks about it, if you derivate with respect to loss you need derivatives but if you derivate with respect to the residuals (y-y_hat) directly instead, there are multiple residuals and multiple thetas, so you need the Jacobian.

**Comment by AceChuse** [comment]
Thank you for replying me so quickly. It's really helpful. But I still have a problem about the gradient_theta of C(G(z)). I'm so sorry. I did the chain rule by myself. And this is ![my result](https://github.com/FrigEgg/Here/blob/master/my%20gradient.png). But there is not C(G(z)) in it. I can't find where I got it wrong.

**Comment by AlexiaJM** [comment]
Second error I do >_<, good thing I have fellow Githubers to tell me my mistakes. Thank you very much! You are indeed right, the good news is it doesn't change anything, thank god... I'll have it corrected in one or two days. Btw, you can use imgur next time if you want to upload an image.

**Comment by AceChuse** [comment]
Thank you so much!
