### ISSUE TITLE
Should TensorBoard still be disabled?

### ISSUE THREAD

**Issue by FeepingCreature** [AlexiaJM/RelativisticGAN#5]
Hi,
I'd noticed the disabled tensorboard logging code, stating it was incompatible with tensorflow. However, since the code doesn't seem to be using tensorflow, why not turn it back on? It seems to work fine when I try.

**Comment by AlexiaJM** [comment]
Tensorflow is used separately to calculate the FID after training a model (see stable.sh and unstable.sh). Tensorflow and Tensorflow-logger are incompatible, I think I had to uninstall TensorBoard logger to get Tensorflow installed. I'll have to recheck that eventually.

**Comment by FeepingCreature** [comment]
Oh, I see. Maybe use [importlib](https://stackoverflow.com/questions/14050281/how-to-check-if-a-python-module-exists-without-importing-it) to check whether logger is installed?

**Comment by AlexiaJM** [comment]
Just checked and nope it's gone so I had to delete it to install TensorFlow. This is sad but there are certainly other ways to log results and personally I don't see the need so much anymore considering that relativism really make things stable so even if loss_D = .00001 all the time, it will still train.

**Comment by FeepingCreature** [comment]
It looks really pretty! :smile:
