### ISSUE TITLE
Suggestion: Use ProGAN in your experiments too.

### ISSUE THREAD

**Issue by akanimax** [AlexiaJM/RelativisticGAN#9]
Hi @AlexiaJM; firstly, great job with your work. I am currently still reading your paper. Just upon scrolling to the FID comparison results, I didn't notice ProGAN (Progressive growing of GANs) in your experiments. The reason why I suggested ProGAN, is that I have recently worked on them and found them to be quite good and stable. Perhaps augmenting the RaLSGAN with Progressive growing, you could achieve an even better FID. This is just a suggestion though. Again great job :+1:.

Best regards,
akanimax

**Comment by AlexiaJM** [comment]
Hi Animesh,

Thanks! I agree but it looks very computationally demanding and I only have a Geforce 1060 which I can run at night. Now that @FrigEgg has added better resuming capabilities to the code, it might be doable though. I could add an overview of other interesting results found by fellow Githubers that are not in the paper in the github page, so feel free to report any interesting results.

**Comment by FeepingCreature** [comment]
Hi my name is FrigEgg I frig eggs :ok_hand: :egg: :+1: :egg:

:smiley:
